config/routes.rb
Dub::Application.routes.draw do
  resources :stylins

  get "welcome/index"

  match 'projects/:id/format' => 'projects#format'

  resources :subs
  resources :projects

   root :to => 'welcome#index'

end

app/models/project.rb
class Project
  include MongoMapper::Document

  key :title, String
  key :description, String
  key :organization, String
  key :create_date, DateTime
  key :start_date, String
  key :end_date, String
  key :status, Hash
  key :vidUrl, String
  key :vidType, String
end

app/models/stylin.rb
class Stylin
  include MongoMapper::Document


end

app/models/sub.rb
class Sub
  include MongoMapper::Document

  key :sTime, String
  key :eTime, String
  key :sourceLang, String
  key :transLang, String
  key :source, String
  key :trans, String
  key :projectId, String

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index 
    #provide an initial splash page, and don't let mongo load the everything...
    @projects = nil

    conditions = {} #Better filter methods?  This seems dumb
    if params[:title] and !params[:title].empty?
      conditions[:title] = { "$regex" => params[:title], "$options" => "-i" } 
    end
    if params[:state] and !params[:state].empty?
      conditions[:state] = { "$regex" => params[:state], "$options" => "-i" } 
    end

    #Pagination... but how do I get a count back without looking up the count?
    @projects = Project.paginate(
      :conditions => conditions,
      :per_page => params[:per_page] ? params[:per_page].to_i : 100,
      :page     => params[:page]     ? params[:page].to_i     : 0,
      :order    => 'id dsc'
    )
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end 
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def format
    @subs = nil;
    if(params[:id])
      @subs = Sub.all(:conditions => {:projectId => params[:id]})
    else
      throw "Error, you must provide a projectId"
    end
    @subs = @subs.sort_by{|k| k['sTime'].to_d}
     
    format = 'webvtt'
    if(!params[:format] or (params[:format] == 'webvtt'))
      @output = format_web_vtt(@subs)
      if(!params[:debug])
         send_data "#{@output}", :filename => 'subs.vtt'
         return
      end
    end
  end

  def format_ass(subs)
    return ''
  end

  def format_web_vtt(subs)
    output = "WEBVTT\n\n"
    @subs.each{ |sub|
      trans = sub['trans'] ? sub['trans'].to_s : nil
      if(trans != nil)
        output += sub.sTime + " --> " + sub.eTime + "\n"
        output += trans + "\n\n"
      end
    }
    return output
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/stylins_controller.rb
class StylinsController < ApplicationController
  # GET /stylins
  # GET /stylins.json
  def index
    @stylins = Stylin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stylins }
    end
  end

  # GET /stylins/1
  # GET /stylins/1.json
  def show
    @stylin = Stylin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stylin }
    end
  end

  # GET /stylins/new
  # GET /stylins/new.json
  def new
    @stylin = Stylin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stylin }
    end
  end

  # GET /stylins/1/edit
  def edit
    @stylin = Stylin.find(params[:id])
  end

  # POST /stylins
  # POST /stylins.json
  def create
    @stylin = Stylin.new(params[:stylin])

    respond_to do |format|
      if @stylin.save
        format.html { redirect_to @stylin, notice: 'Stylin was successfully created.' }
        format.json { render json: @stylin, status: :created, location: @stylin }
      else
        format.html { render action: "new" }
        format.json { render json: @stylin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stylins/1
  # PUT /stylins/1.json
  def update
    @stylin = Stylin.find(params[:id])

    respond_to do |format|
      if @stylin.update_attributes(params[:stylin])
        format.html { redirect_to @stylin, notice: 'Stylin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stylin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stylins/1
  # DELETE /stylins/1.json
  def destroy
    @stylin = Stylin.find(params[:id])
    @stylin.destroy

    respond_to do |format|
      format.html { redirect_to stylins_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  # GET /subs
  # GET /subs.json
  def index
    @subs = nil;
    if(params[:projectId])
      @subs = Sub.all(:conditions => {:projectId => params[:projectId]})
    else
      throw "Error, you must provide a projectId"
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subs }
    end
  end

  # GET /subs/1
  # GET /subs/1.json
  def show
    @sub = Sub.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sub }
    end
  end

  # GET /subs/new
  # GET /subs/new.json
  def new
    @sub = Sub.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sub }
    end
  end

  # GET /subs/1/edit
  def edit
    @sub = Sub.find(params[:id])
  end

  # POST /subs
  # POST /subs.json
  def create
    @sub = Sub.new(params[:sub])

    respond_to do |format|
      if @sub.save
        format.html { redirect_to @sub, notice: 'Sub was successfully created.' }
        format.json { render json: @sub, status: :created, location: @sub }
      else
        format.html { render action: "new" }
        format.json { render json: @sub.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subs/1
  # PUT /subs/1.json
  def update
    @sub = Sub.find(params[:id])

    respond_to do |format|
      if @sub.update_attributes(params[:sub])
        format.html { redirect_to @sub, notice: 'Sub was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sub.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subs/1
  # DELETE /subs/1.json
  def destroy
    @sub = Sub.find(params[:id])
    @sub.destroy

    respond_to do |format|
      format.html { redirect_to subs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/stylins_helper.rb
module StylinsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dub</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :organization %><br />
    <%= f.text_field :organization %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.text_field :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.text_field :end_date %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
  <div class="banner"><div>

  <div ng-app='dub' ng-controller="ProjectEntry" id="main" class="main">
      <!-- Navbar, TODO: add google translate options here? -->
      <div id="topBar" class="navbar navbar-inner">
        <!-- Title information -->
        <div class="span4">
          <span class="brand">{{gT('Title')}}</span>
          <input class="span3 m5" type="text"
              ng-model="project.ResourceProject.title" 
              ng-focus="keypress.sleep()"
              ng-change="project.update()"  
              placeholder="{{gT('No Name?')}}"
          /> 
        </div>
        <!-- Status information -->
        <div class="span6">
          <span class="brand">{{gT('Status')}}</span>
          <div class="span4 m5">
            <status></status>
          </div>
        </div>
        <!-- Key handling widget -->
        <keyhandler keypress=keypress></keyhandler> 
      </div>
      <!-- Top level container for the rest of the page elements -->
      <div class="container-fluid">
        <div class="row-fluid">

          <!-- Placeholder for where we are going to insert the video -->
          <videomanager></videomanager>

          <!-- For editing the subtitle that you select -->
          <div id="subtitles" class="span5">

            <!-- Editing container -->
            <div class="container-fluid well">
              <div id="subcontrols" class="navbar">
                <span class="brand">{{gT('Editing')}}</span>
                <button ng-click="action.newSub()" 
                  title="{{gT(i18n.NewSub)}}" id="new" class="btn" >
                  <i class="icon-plus"></i>
                </button>
                <button  ng-click="action.endSub()"
                  title="{{gT('End the current subtitle')}}" id="end" class="btn">
                  <i class="icon-ok"></i>
                </button>
                <button ng-click="action.pauseAndEndSub()" 
                  title="{{gT('End and Pause')}}" class="btn" >
                  <i class="icon-ok"></i>
                  <i class="icon-pause"></i>
                </button>
                <button ng-click="action.splitSub()" 
                  title="{{gT('Split the currently selected sub')}}" class="btn" >
                  <i class="icon-resize-full"></i>
                </button>
                <button  ng-click="action.removeSub()"
                  title="{{gT('Remove the currently selected sub')}}" class="btn">
                  <i class="icon-trash"></i>
                </button>

                <!-- Style editor for just a single subtitle (hidden unless a sub is active) --> 
                <div class="pull-right" 
                  ng-init="stylinType='Sub';"
                  ng-hide="!project.subs.curr">

                  <substylin stylin=stylin resource=project.subs.curr></substylin>
                </div>
              </div>

              <!-- Editing a set of subtitles -->
              <div class="row-fluid">
                <input id="source" type="text" class="span13" placeholder="Source" 
                  ng-focus="keypress.sleep()"
                  ng-change="action.changeSub()" 
                  ng-model="project.subs.curr.source" 
                  ng-disabled="!project.subs.curr"
                /> 
              </div>
              <div class="row-fluid">
                <input id="translation" type="text" class="span13" placeholder="Translation" 
                  ng-focus="keypress.sleep()"
                  ng-change="action.changeSub()" 
                  ng-model="project.subs.curr.trans" 
                  ng-disabled="!project.subs.curr"
                /> 
              </div>

              <!-- Editing controls for a subtitle that is currently active -->
              <div class="row-fluid">
                <form class="navbar-form pull-left">
                  <button  title="Jump to Sub Start." type="button" class="btn m5"
                    ng-click="action.jumpStart()" 
                    ng-disabled="!project.subs.curr"
                  >    
                    <i class="icon-fast-backward"></i>
                  </button>
                  <button title="Set Sub to Video Time."  type="button" class="btn m5" 
                    ng-click="action.setStart()"
                    ng-disabled="!project.subs.curr"
                  >
                    <i class="icon-time"></i>
                  </button>
                  <input type="time" class="span3" placeholder="{{gT('Start')}}"
                    ng-change="action.changeSub()" 
                    ng-focus="keypress.sleep()"
                    ng-model="project.subs.curr.sTime" 
                    ng-disabled="!project.subs.curr"
                  /> 
                  <input type="time" class="span3" placeholder="{{gT('End')}}" 
                    ng-change="action.changeSub()" 
                    ng-focus="keypress.sleep()"
                    ng-model="project.subs.curr.eTime"   
                    ng-disabled="!project.subs.curr"
                  /> 
                  <button title="{{gT('Set subtitle end to current video time.')}}" type="button" class="btn m5"
                    ng-click="action.setEnd()" 
                    ng-disabled="!project.subs.curr"
                  >
                    <i class="icon-time"></i>
                  </button>
                  <button  title="{{gT('Jump video to end time for subtitle')}}" class="btn m5"
                    ng-click="action.jumpEnd()" 
                    ng-disabled="!project.subs.curr"
                  >
                    <i class="icon-fast-forward"></i>
                  </button>
                </form>
              </div>
            </div>

            <!-- Style elements in the project -->
            <projstylin project=project stylin=stylin> </projstylin>

            <!-- A listing of all the existing subtitles, can click to select them -->
            <div id="subtitle" class="well">
              <ul class="nav nav-list">
                <li class="nav-header">{{gT('Subtitles')}}</li>
                <li class="{{project.controls.isActive(sub)}}" ng-repeat="sub in project.subs.arr"> <!-- Click selection should make current -->
                <a id="sub_{{sub.id}}"  ng-click="project.controls.setCurrent(sub);"> <!-- apply class active if active -->
                  [{{sub.sTime}} - {{sub.eTime}}]</br>
                  {{sub.source}}
                    <br/>
                  {{sub.trans}}
                </a>
                </li>
              </ul>
            </div>


          </div> <!-- End subtitles sub container -->

        </div><!-- End Span container -->
      </div> <!-- End container fluid -->
    </div> <!-- End ng controller -->

    <!-- All the script includes -->
    <script type="text/javascript">
      DubMark.Config.base.url = 'http://localhost\\:3000/';
      DubMark.Config.PageConfig = JSON.parse(decodeURIComponent('<%= @project.to_json.html_safe =%>'));
    </script>

app/views/projects/format.html.erb
<pre>
<%= @output %>
</pre>

app/views/projects/index.html.erb
<div class="banner"></div>

<!-- Probably want to make this entire thing into a template -->
<div ng-app='dub' ng-controller="ProjectListings" class="listings container-fluid ">
  <div class="row-fluid">
    <div class="span6">
      <div class="navbar navbar-inner">
      <form class="span13 navbar-form">
        <span class='brand'>Projects</span>

          <!-- Used in jQuery dialog, could just make this into another angular module?" -->
          <create></create>
          
          <!-- TODO: Make the UI actually have a proper pagination counter... 
          sadly counts in mongo are actually expensive? -->
          &nbsp;
          &nbsp;
          &nbsp;
          <button title='Previous' ng-click="list.prev()"    class="btn">
            <i class="icon-step-backward"></i>
          </button>

          <button title='Refresh'  ng-click="list.refresh()" class="btn">
            <i class="icon-refresh"></i>
          </button>

          <button title='Next'     ng-click="list.next()"    class="btn">
            <i class="icon-step-forward"></i>
          </button>


          <button title='Search'   ng-click="list.search()"  class="btn pull-right">
            <i class="icon-search"></i>
          </button>
          <input type="text" ng-model="list.filterTitle" ng-change="list.filterChange()"
                 class="pull-right" placeholder="Filter projects"> </input>
      </form>
      </div>

      <table class="table table-striped">
        <thead>
        <tr>
          <td>Title</td>
          <td>Status</td>
          <td>Created</td>
        </tr>
        </thead>
        <tbody>
          <tr class='{{list.isActive(proj)}}' 
            ng-repeat="proj in list.arr" 
            ng-click="list.setActive(proj)" 
            ng-dblclick="list.openActive()"> 
          <td>{{proj.title}}</td>
          <td>
            <status ng-scope=proj></status>
          </td>
          <td>
            <span>{{proj.create_date}}</span>
          </td>
        </tr>
        </tbody>
      </table>
    </div>

    <!-- Information about the currently selected project. (make into a widget)-->
    <div class="span6 project_info">
      <div class="navbar navbar-inner">
        <span class='brand'> Project Information: {{list.active.title}}</span>
        <button  class="btn pull-right" title="Open to edit" 
          ng-disabled="!list.active"
          ng-click="list.openActive()"
         >
        <i class="icon-edit"></i>
        </button>
      </div>
      <div class="container-fluid">
        <input class="span6" type='text' placeholder="{{gT('Project')}}" title="{{gT('Project title')}}"
          ng-disabled="!list.active"
          ng-model=list.active.title
          ng-change="list.changeProject()"
        >
        <div class="span5 image-project pull-right">
          Image {{list.active.imageUrl}}
        </div>
        <div class="row-fluid">
          <input class="span6" type='text' placeholder="{{gT('Translator')}}" title="{{gT('Translator')}}"
            ng-disabled="!list.active"
            ng-model=list.active.translator 
            ng-change="list.changeProject()"
          />
        </div>
        <div class="row-fluid">
          <input  class="span6" type='text' placeholder="{{gT('Published link')}}" title="{{gT('Published link')}}"
            ng-disabled="!list.active"
            ng-model=list.active.link 
            ng-change="list.changeProject()"
          />
        </div>
        <div class="row-fluid">
          <textarea class="span6" type='text' placeholder="{{gT('Notes')}}" title="{{gT('Notes')}}"
            ng-disabled="!list.active"
            ng-model=list.active.notes
            ng-change="list.changeProject()"
          >
          </textarea>
        </div>
      </div>

    </div>
  </div>

</div> <!-- End main controller section -->

<script type="text/javascript">
  DubMark.Config.base.url = 'http://localhost\\:3000/';
  //DubMark.Config.base.url = 'http://10.100.116.252\\:3000/';
  DubMark.Config.PageConfig = {
    data: JSON.parse(decodeURIComponent('<%= @projects.to_json.html_safe() =%>'))
  };
</script>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @project.title %>
</p>

<p>
  <b>Description:</b>
  <%= @project.description %>
</p>

<p>
  <b>Organization:</b>
  <%= @project.organization %>
</p>

<p>
  <b>Start date:</b>
  <%= @project.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @project.end_date %>
</p>

<p>
  <b>Status:</b>
  <%= @project.status %>
</p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/projects/show.json.erb
<%= @project.to_json %> 

app/views/stylins/_form.html.erb
<%= form_for(@stylin) do |f| %>
  <% if @stylin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stylin.errors.count, "error") %> prohibited this stylin from being saved:</h2>

      <ul>
      <% @stylin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stylins/edit.html.erb
<h1>Editing stylin</h1>

<%= render 'form' %>

<%= link_to 'Show', @stylin %> |
<%= link_to 'Back', stylins_path %>

app/views/stylins/index.html.erb
<h1>Listing stylins</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stylins.each do |stylin| %>
  <tr>
    <td><%= link_to 'Show', stylin %></td>
    <td><%= link_to 'Edit', edit_stylin_path(stylin) %></td>
    <td><%= link_to 'Destroy', stylin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Stylin', new_stylin_path %>

app/views/stylins/new.html.erb
<h1>New stylin</h1>

<%= render 'form' %>

<%= link_to 'Back', stylins_path %>

app/views/stylins/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_stylin_path(@stylin) %> |
<%= link_to 'Back', stylins_path %>

app/views/subs/_form.html.erb
<%= form_for(@sub) do |f| %>
  <% if @sub.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sub.errors.count, "error") %> prohibited this sub from being saved:</h2>

      <ul>
      <% @sub.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sTime %><br />
    <%= f.text_field :sTime %>
  </div>
  <div class="field">
    <%= f.label :eTime %><br />
    <%= f.text_field :eTime %>
  </div>
  <div class="field">
    <%= f.label :sourceLang %><br />
    <%= f.text_field :sourceLang %>
  </div>
  <div class="field">
    <%= f.label :transLang %><br />
    <%= f.text_field :transLang %>
  </div>
  <div class="field">
    <%= f.label :source %><br />
    <%= f.text_field :source %>
  </div>
  <div class="field">
    <%= f.label :trans %><br />
    <%= f.text_field :trans %>
  </div>
  <div class="field">
    <%= f.label :projectId %><br />
    <%= f.text_field :projectId %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subs/edit.html.erb
<h1>Editing sub</h1>

<%= render 'form' %>

<%= link_to 'Show', @sub %> |
<%= link_to 'Back', subs_path %>

app/views/subs/index.html.erb
<h1>Listing subs</h1>

<table>
  <tr>
    <th>Stime</th>
    <th>Etime</th>
    <th>Sourcelang</th>
    <th>Translang</th>
    <th>Source</th>
    <th>Trans</th>
    <th>Projectid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subs.each do |sub| %>
  <tr>
    <td><%= sub.sTime %></td>
    <td><%= sub.eTime %></td>
    <td><%= sub.sourceLang %></td>
    <td><%= sub.transLang %></td>
    <td><%= sub.source %></td>
    <td><%= sub.trans %></td>
    <td><%= sub.projectId %></td>
    <td><%= link_to 'Show', sub %></td>
    <td><%= link_to 'Edit', edit_sub_path(sub) %></td>
    <td><%= link_to 'Destroy', sub, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sub', new_sub_path %>

app/views/subs/new.html.erb
<h1>New sub</h1>

<%= render 'form' %>

<%= link_to 'Back', subs_path %>

app/views/subs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Stime:</b>
  <%= @sub.sTime %>
</p>

<p>
  <b>Etime:</b>
  <%= @sub.eTime %>
</p>

<p>
  <b>Sourcelang:</b>
  <%= @sub.sourceLang %>
</p>

<p>
  <b>Translang:</b>
  <%= @sub.transLang %>
</p>

<p>
  <b>Source:</b>
  <%= @sub.source %>
</p>

<p>
  <b>Trans:</b>
  <%= @sub.trans %>
</p>

<p>
  <b>Projectid:</b>
  <%= @sub.projectId %>
</p>


<%= link_to 'Edit', edit_sub_path(@sub) %> |
<%= link_to 'Back', subs_path %>